### ISSUE TITLE
Meta tags - URL Preview

### ISSUE THREAD

**Issue by HarishReddyCH** [staylor/react-helmet-async#160]
URL Preview is not working when adding meta tags using **Helmet**

Please check this to know about [URL/Link Preview](https://www.npmjs.com/package/@dhaiwat10/react-link-preview)

**CODE:**
     `<Helmet>
        <title>Sample Page</title>
        <meta name="description" content="Sample description." />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="Test Site" />
        <meta property="og:image" content="https://us.123rf.com/450wm/andyadi/andyadi1802/andyadi180200513/95572662-vector-logo-design-for-beauty-salon-dermatology-center-and-wellness-house-.jpg?ver=6" />
      </Helmet>`

**Expected output:**
Meta tags data which I given in **Helmet** should be shown in link preview.

**Comment by hoangman1108** [comment]
the same issue

**Comment by hoangman1108** [comment]
home they fix this problem soon

**Comment by rrodwell** [comment]
Any update on this?

**Comment by apnnux** [comment]
the same issue

**Comment by Antonio112009** [comment]
I believe the problem is related to the use of render mode "SPA". Google bot, Social media preview and others are loading firstly bare bone "index.html" file which does not **statically** contains all your **dynamical** changes on **client side**.

The approach that you are looking for is eighter "SSR" (Server Side Rendering) or "SSG" (Static-Site Generator).

Great explanation of these modes you can [find here](https://vite-plugin-ssr.com/SPA-vs-SSR) and I believe the vite-plugin-ssr will suit your project.

To conclude, in the documentation it mentioned that you have to use server-side rendering in order to have appropriate work of the application, because the tags must be already in the index.html file **before** a client will receive all necessary files (index.html, main.bundle.xxx.js, image.png, and etc).



(Please note that this is explanation for those who have not been using other render methods before)

**Comment by SanNic20** [comment]
The same issue

I know the problem of crawlers not executing JS.

I looked into multiple solution like combining react-snap and react-helmet but that only works at build time.

Migrating to SSR like NextJS is not an option for me.

Any suggestions, other approaches are appreciated.

Thanks

**Comment by staylor** [comment]
the HTML source of the page needs to contain the tags

**Comment by hussainsah** [comment]
**Issue: Meta Tags Not Appearing in "View Page Source" When Using react-helmet-async**  

I have built a site using React 18 with Vite. The site includes user input forms, data fetching with React Query, and uses `react-helmet-async` for managing meta tags. However, when I check the "View Page Source," the meta tags are not present.  

I've reviewed various comments and discussions on this issue but haven't found a definitive solution. Given this, I am considering different rendering strategies:  
- **SPA (Single Page Application)**  
- **SSR (Server-Side Rendering)**  
- **Pre-rendering (SSG - Static Site Generation)**  
- **HTML-only (if applicable in React 18, though I suspect it may not be)**  

Which approach would be best for ensuring that meta tags are correctly rendered in the page source? Any insights or recommendations would be greatly appreciated.  

Thank you!
