### ISSUE TITLE
alpha only error

### ISSUE THREAD

**Issue by antonybudianto** [staylor/react-helmet-async#21]
Hi,

I just installed the alpha version `0.1.0-alpha` (latest tag), but I got:
```sh
: Uncaught TypeError: Cannot read property 'add' of undefined
```

It works well with `0.1.0` though.

I appreciate any help :pray:

**Comment by antonybudianto** [comment]
You can use https://github.com/antonybudianto/react-kits to reproduce, just update react-helmet-async to alpha, and do:
```sh
yarn
yarn bootstrap
yarn build:lib
yarn temp:start
```
visit http://localhost:3000 and error will be thrown

**Comment by staylor** [comment]
seems like your `getInitialData()` function is traversing a tree that does not contain `<HelmetProvider>`. On the server, you can see you are only injecting it after the fact.

**Comment by antonybudianto** [comment]
Did you mean this one?
https://github.com/antonybudianto/react-kits/blob/repro-alpha/packages/react-kits-cli/template/src/routes/index.js#L10

**Comment by antonybudianto** [comment]
I didn't kknow what's causing it since it worked well on `v0.1.0`, but not working on `v0.1.0-alpha`

**Comment by chenxsan** [comment]
I had a simillar use case having the same error. The problem in my case is because I'm running two `react-helmet-async` packages, one for server and one for client, seems they don't share the same `context` value from `Context.js` module. Thought it's a bug needs fix. The new react `Context` was introduced in https://github.com/staylor/react-helmet-async/commit/cc04ce807e425689c185969157d69d31cff0dd94, so you'd better lock the version to `0.1.0` right now.

**Comment by staylor** [comment]
See #25, comments on #27
